### ISSUE TITLE
I made 2 models to do inference using inference server,but failed.

### ISSUE THREAD

**Issue by YabDl** [NVIDIA/dl-inference-server#1]
I made 2 models to do inference using inference server.
1.One of them is caffemodel,converted to .engine model using the code in [https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#caffeworkflow](url)
.And I renamed it by model.plan,but an error came out.
![6](https://user-images.githubusercontent.com/34618977/39856946-4e4461fa-5464-11e8-96bf-88b9c03899af.PNG)
2.another one come from the digits's job file after training, is a .graph_def file and renamed model.graphdef by me, the result is showed below.
![_20180509100713](https://user-images.githubusercontent.com/34618977/39857180-fbfaf0f2-5464-11e8-8248-4e830557ebbc.png)
I don't know how to deal with these bugs, please help me.

**Comment by deadeyegoodwin** [comment]
For 1, it appears you have generated your TensorRT engine using a different version of TensorRT than what is supported by the inference server. The 18.04 version of the inference server uses TensorRT 3.0.4 so you need to use that same version when creating an engine.

For 2, it appears your model makes use of a custom PyFunc operation. The inference server currently has no way of executing that custom operation.
