### ISSUE TITLE
fetch_models.sh uses wget but files are git lfs

### ISSUE THREAD

**Issue by cliveseldon** [NVIDIA/dl-inference-server#11]
https://github.com/NVIDIA/dl-inference-server/blob/06f9e053c7d0bac1239a44f1ca8a7722983ef596/examples/fetch_models.sh#L32-L35

Probably need to update the script to fetch the actual files.

**Comment by deadeyegoodwin** [comment]
This seems to have broken at some point... perhaps github no longer makes the file available by wget. We need to revisit the example model store to use git lfs or find different publically available models to pull. Feel free to submit a patch.
