### ISSUE TITLE
Model config example for tensorflow SavedModel 

### ISSUE THREAD

**Issue by xinli94** [NVIDIA/dl-inference-server#14]
Hi,

Could you please give an example of model configuration file for tensorflow savedmodel? Sorry could not find any reference. I am using the MNIST data classification example `https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_saved_model.py` to export my model. But could not get it served using inference sever. 

Thanks so much for your help!

Best,
Xin

**Comment by xinli94** [comment]
To be more specific, how should I modify the `config.pbtxt` to make it work for string type input?

**Comment by deadeyegoodwin** [comment]
Currently the inference server doesn't support string inputs. It is surprising that an mnist model has a string input. Usually it is just a [1,28,28] tensor representing the input image. Can you share the config.pbtxt you are trying to use?

**Comment by xinli94** [comment]
Yes sure!

```name: "mnist"
platform: "tensorflow_savedmodel"
max_batch_size: 128
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 28, 28, 1 ]
    format: FORMAT_NHWC
  }
]
output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ 10 ]
    label_filename: "labels.txt"
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 1,
    gpus: [ 0 ]
  }
]```

**Comment by xinli94** [comment]
Actually is it possible to make the inference server support string inputs? Because the inputs would be much smaller, if we just need to send `encoded_image_string`. And also can avoid doing image decoding one the client side. Or is there any other approach?

**Comment by deadeyegoodwin** [comment]
When you say "string" you seem to mean an image. You can send in an image (or any binary blob) with a 1-dimensional tensor. But the model will need to know what to do with that blob. Currently the inference server has no built-in pre/post processing. It simply routes the input tensors to the model. We are working on ways to local pre/post processing closer to the inferencing to avoid I/O overheads but in the current server there is nothing implemented.

You can look at the image_client example in this repo. It will perform all the pre/post processing needed for an image classification network like you have. For your mnist model you should be able to use it out-of-the-box.

**Comment by xinli94** [comment]
Thanks for the reply! 

Yes by string I mean an encoded_image (like outputs of python's f.read()). And what I am trying to do is hitting the inference server from a NodeJS client, so it is kind of tricky to do the preprocessing in NodeJS. Thanks so much for your suggestions though!

**Comment by xinli94** [comment]
> When you say "string" you seem to mean an image. You can send in an image (or any binary blob) with a 1-dimensional tensor. But the model will need to know what to do with that blob. Currently the inference server has no built-in pre/post processing. It simply routes the input tensors to the model. We are working on ways to local pre/post processing closer to the inferencing to avoid I/O overheads but in the current server there is nothing implemented.
> 
> You can look at the image_client example in this repo. It will perform all the pre/post processing needed for an image classification network like you have. For your mnist model you should be able to use it out-of-the-box.

Actually i am wondering how can we send in an `1-dimensional tensor` - which input format should we specify in model config? Is it still of a fixed size? Is there any plan to support `variable-dims` inputs?
