### ISSUE TITLE
Is there any plan to support variable-dims inputs

### ISSUE THREAD

**Issue by xinli94** [NVIDIA/dl-inference-server#15]
Hi,

I am working on using inference-server to serve some of my models. So I am running into this issue: my model is trained with some preprocessing which expects a variable-size image. I got huge accuracy discrepancy if I do the `decode and resize` on the client side.

Is there any plan to support variable-dims inputs?

Best,
Xin

**Comment by xinli94** [comment]
For example, for the (correct) preprocessing I was using `tf.image.resize_bilinear(image, [299, 299], align_corners=False)`. 

This is from the official inception preprocessing `https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/inception_preprocessing.py#L277`, which is used very frequently for *inception* model implemented in tensorflow. And it is the same for *VGG* models.

But I cannot do that resizing in my NodeJS / c++ client. Because I cannot call tensorflow's function, and it is a known issue that `tf.image.resize` does something bad `https://github.com/tensorflow/tensorflow/issues/6720`, which cannot be implemented with `cv2` or `PIL` as far as I know.

Hopefully using a variable-dims image (which means: decoded, but not resized yet) as input will fix everything! Or even better, a string-type encoded image as I pointed out previously.

Thanks so much for your help!!
Xin

**Comment by deadeyegoodwin** [comment]
We don't have any immediate plans to support variable dimensions but it is on the roadmap. But from your description it sounds like you still want to send the image directly to the inference server. The case you described is exactly what the image_client example does, using either C++ or Python. It will resize, scale, etc. any image to the format expected by the image classification model and then send the resulting input tensor to the server for inferencing. The example directory includes a resnet50 model that you can experiment with. image_client will also work for VGG and inception models. Have you tried using image_client with your model?

**Comment by xinli94** [comment]
Thanks for the reply! 

Yes I did used the image client, the problem is this part `https://github.com/NVIDIA/dl-inference-server/blob/18.09/src/clients/c%2B%2B/image_client.cc#L90`. So the resized results are different when I use `cv2`, compared to using `tf.image.resize_bilinear` in the exported graph.

And the resnet50 model works perfectly for me! It is something bad about tensorflow that we cannot do in the client side.
