### ISSUE TITLE
tensorrtserver-0.6.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by Robbie-Palmer** [NVIDIA/dl-inference-server#18]
I've been unable to get a build of the Python client installed by following the README instructions
I using Python version 3.5.2 on Ubuntu version 16.04

When running the command `make -f Makefile.clients all pip` 
I get the error
```
/bin/sh: 1: autoreconf: not found
Makefile:1376: recipe for target 'third_party/protobuf/configure' failed
make[1]: *** [third_party/protobuf/configure] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/user/repositories/dl-inference-server/build/grpc/grpc'
Makefile.clients:121: recipe for target '/home/user/repositories/dl-inference-server/build/grpc/libgrpc_indicator' failed
make: *** [/home/user/repositories/dl-inference-server/build/grpc/libgrpc_indicator] Error 2
```
Also when running the command
`pip install --no-cache-dir --upgrade build/dist/dist/tensorrtserver-0.6.0-cp27-cp27mu-linux_x86_64.whl`
libopencv-dev would not install with the following message
```
The following packages have unmet dependencies.
 libopencv-dev : Depends: libopencv-objdetect-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libopencv-highgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libopencv-legacy-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libopencv-contrib-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libopencv-videostab-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libopencv-superres-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libopencv-ocl-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libcv-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libhighgui-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
                 Depends: libcvaux-dev (= 2.4.9.1+dfsg-1.5ubuntu1.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I don't know if this is linked to the above error or not, I have opencv-python installed which might be causing the issue

Figuring this is an environmental problem I successfully got a build of the wheel using docker as outlined in the README, but when I do `pip install tensorrtserver-0.6.0-cp35-cp35m-linux_x86_64.whl` I get the error
`tensorrtserver-0.6.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.`

I assumed this would be to do with my machine's architecture or ABI, but I've checked and it's an exact match for the wheel
```python
pep425tags.get_impl_tag()
'cp35'
pep425tags.get_abi_tag()
'cp35m'
pep425tags.get_platform()
'linux_x86_64'
```

**Comment by deadeyegoodwin** [comment]
Since it builds correctly inside a base ubuntu 16.04 container I think it is likely something on your host system that is causing the build to fail. Are you sure you have "autoconf" package installed? That installs /usr/bin/autoreconf which your log shows as being "not found". 

When you try to install the whl and get "The following packages have unmet dependencies" that likely means you have something broken in your host system package management. You definitely need to get that fixed and get the required packages installed on your host system.

We'll look to add some more testing with different python versions and make sure the resulting python package installs correctly.

**Comment by deadeyegoodwin** [comment]
Another thing you can try is to use "pip3" when you install tensorrtserver-0.6.0-cp35-cp35m-linux_x86_64.whl. Since it is a "python3" whl you likely need to use pip3.

**Comment by Robbie-Palmer** [comment]
Thank-you for responding so quickly, and sorry for leaving this for so long, I've only been able to get back to working on this now
There seemed to be something very wrong with my environment; I had a windows machine, and successfully installed the wheel on WSL and contacted the server running on the Ubuntu machine
I've re-installed Ubuntu and can now successfully run the server and clients on the same machine, so issue is resolved 😄
