### ISSUE TITLE
How can we specify the model version or inference on all version of the model?

### ISSUE THREAD

**Issue by giranntu** [NVIDIA/dl-inference-server#22]
In [https://docs.nvidia.com/deeplearning/sdk/inference-user-guide/index.html#versions](url)
We describe in document:

 **All**
     All versions of the model that are specified in the model repository are available for inferencing.
 **Latest**
     Only the latest n versions of the model specified in the model repository are available for inferencing. The latest versions of the model are the numerically greatest version numbers.
  **Specific**
     The specifically listed versions of the model are available for inferencing.

It would be nice if you guide that where could we get to specify the model version that we want to inference?

Because for now when I have 4 versions of current model in the folder, and named as 
```

 model_1/
        config.pbtxt
        output0_labels.txt
        output1_labels.txt
     0/
          model.graphdef
     1/
          model.graphdef
     2/
          model.graphdef    
     3/
          model.graphdef
```

Only latest version works. And we can not infer by previous version, how could I solve that?

**Comment by deadeyegoodwin** [comment]
You need to set the "All" version policy in config.pbtxt if you want all versions of the model to be available. What does your config.pbtxt look like? Does it have this line: "version_policy: { all { }}"

The default version policy only exposes the most recent (highest-numbered) version.

**Comment by deadeyegoodwin** [comment]
Note that the entire TensorRT Inference Server has been open-sourced at https://github.com/NVIDIA/tensorrt-inference-server. There is also new documentation there that you could check to see if it is more clear in this regard. If not let us know on that issue board.

This repo is no longer accepting changes and will soon be closed so please move all future work to https://github.com/NVIDIA/tensorrt-inference-server.
