### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/dl-inference-server#9]
I would like to call the inference server from windows similar to how the nvidia-gre project provides a curl request interface for providing an image path. Will there be future support for the clients of this?

**Comment by deadeyegoodwin** [comment]
There is an example image_client application (both C++ and Python versions) in this repo that shows how to talk to the inference server using the Inference Server Client Library (the source for that is also included in this repo). We haven't tried building those on Windows but it is likely not too difficult to do that (we'd like to hear your experience if you try).

Your question sounds like you would be most interested in the image_client. It allows you to specify an image (or starting in 18.09 a directory of images) and a model name and then sends a request to the inference_server to perform inference on that image using that model (the model must be an image classification type model). 

Is that the functionality you are looking for?

**Comment by rperdon** [comment]
Yes this is the functionality I am looking for. I examining the c++ code, I saw the #include <unistd.h> which is usually a header for unix ports. I have yet to get deeper into the code, but think that the code can be stripped down to bare essentials where we just need to call the server and provide the numpy matrix of the image and get inference of that. Perhaps some documentation on how to "call" the inference server or provide data that is agnostic to the inference server API.

**Comment by deadeyegoodwin** [comment]
The simplest path is likely to use the gRPC generated client APIs (generated by protoc compiler) as shown in the https://github.com/NVIDIA/dl-inference-server/blob/18.09/src/clients/python/grpc_image_client.py example. That example doesn't rely on any C++ code. You just need to run protoc against the *.proto files to generate the grpc python client library. The Makefile shows how we run protoc which should be same/similar for windows. If you know the size and names of your input and output tensors you can create the request protobuf and just call the grpc Infer API.

See also https://docs.nvidia.com/deeplearning/sdk/inference-user-guide/index.html#grpc-api

**Comment by rperdon** [comment]
I require some pointers on how to run protoc against the *.proto files in windows. I see the makefile and the lines directing the proto files  there but its not entirely clear to me as to how to proceed.

**Comment by rperdon** [comment]
I see TensorRT 5.0 has been released and the client updated. TensorRT 5.0 indicates windows support. 

https://developer.nvidia.com/tensorrt

Will there be some more guidelines on how to get an inference call from windows up and running? I am currently exploring how to make this work, but a guideline would be appreciated.

**Comment by deadeyegoodwin** [comment]
The page you reference is for the TensorRT Inference Accelerator (basically a compiler and runtime for accelerating inferencing on GPUs). TensorRT Inference Server is a containerized micro-service that performs inferencing for different model types, including models generated by the TensorRT Inference Accelerator.

We understand your request for windows build instructions for the examples and libraries included in this repo. We have it planned for the future but unfortunately we don't have anything to give you right now. This project consists of "standard" C++ and Python sources so the solution is just a "standard" port from linux to windows.

**Comment by deadeyegoodwin** [comment]
The entire TensorRT Inference Server has been open-sourced at https://github.com/NVIDIA/tensorrt-inference-server. We have windows support in our future plans but feel free to re-raise your issue in the new repo.

This repo is no longer accepting changes and will soon be closed so please move all future work to https://github.com/NVIDIA/tensorrt-inference-server.
